### ISSUE TITLE
TODO: remove btcpy source files once pip repo is updated to v0.4.

### ISSUE THREAD

**Issue by LaurentMT** [Samourai-Wallet/boltzmann#15]

**Comment by riordant** [comment]
Project actually does not seem to build under current conditions. I had to remove local btcpy folder and install btcpy 0.4 from source [here](https://github.com/chainside/btcpy/releases/tag/0.4) to get it to work.

**Comment by LaurentMT** [comment]
Seems like our repo is missing some modules from their 0.4.

**Comment by LaurentMT** [comment]
Fixed by commit  #6e2c610
